try {
    hello();        
} catch (errror) {
    console.log(error);
}
try {
    anotherFn();
} catch (error) {
    console.log("Esto es un error");
}